name: PR Checks with Bun

on:
  pull_request:
    branches:
      - main

jobs:
  pr_checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Run App TypeScript Checks
        run: bun run tsc-app
      
      - name: Run Socket TypeScript Checks
        run: bun run tsc-socket

      - name: Run ESLint
        run: bun run lint

      - name: Run Prettier
        run: bun run prettier-check
